import { getStatusLabel, toCanonicalStatusKey } from './statusLabels';

const STATUS_TONES = {
  draft: 'bg-gray-100 text-gray-800',
  submitted: 'bg-blue-100 text-blue-800',
  verified: 'bg-cyan-100 text-cyan-800',
  payment_pending: 'bg-yellow-100 text-yellow-800',
  under_review: 'bg-indigo-100 text-indigo-800',
  hold_complaint: 'bg-red-100 text-red-800',
  hold_clearance: 'bg-amber-100 text-amber-800',
  correction: 'bg-orange-100 text-orange-800',
  sw_review_pending: 'bg-purple-100 text-purple-800',
  endorsed: 'bg-teal-100 text-teal-800',
  committee_review: 'bg-fuchsia-100 text-fuchsia-800',
  approved: 'bg-green-100 text-green-800',
  rejected: 'bg-rose-100 text-rose-800',
  not_granted_appeal_required: 'bg-amber-100 text-amber-800',
  appeal_submitted: 'bg-orange-100 text-orange-800',
  approved_awaiting_agreement: 'bg-emerald-100 text-emerald-800',
  agreement_completed: 'bg-emerald-100 text-emerald-800',
  permit_approved: 'bg-green-100 text-green-800',
  permit_collected: 'bg-green-100 text-green-800',
  coc_pending: 'bg-sky-100 text-sky-800',
  coc_issued: 'bg-emerald-100 text-emerald-800',
  requested: 'bg-yellow-100 text-yellow-800',
  fee_calculated: 'bg-yellow-100 text-yellow-800',
  paid: 'bg-sky-100 text-sky-800',
  assigned_to_to: 'bg-indigo-100 text-indigo-800',
  inspection_complete: 'bg-indigo-100 text-indigo-800',
  coc_violations_found: 'bg-amber-100 text-amber-800',
  coc_correction_required: 'bg-red-100 text-red-800',
  coc_rectification_in_progress: 'bg-amber-100 text-amber-800',
  coc_fine_paid_awaiting_correction: 'bg-amber-100 text-amber-800',
  correction_submitted: 'bg-indigo-100 text-indigo-800',
  reinspection_eligible: 'bg-sky-100 text-sky-800',
  reinspection_requested: 'bg-sky-100 text-sky-800',
  coc_fine_paid_regularization_pending: 'bg-slate-100 text-slate-800',
  coc_rejected_non_rectifiable: 'bg-red-100 text-red-800',
  coc_approved: 'bg-emerald-100 text-green-800',
  coc_collected: 'bg-emerald-100 text-green-800',
  closed: 'bg-slate-200 text-slate-700',
  pending: 'bg-yellow-100 text-yellow-800',
  accepted: 'bg-blue-100 text-blue-800',
  certified: 'bg-green-100 text-green-800',
  completed: 'bg-green-100 text-green-800',
};

const FILTER_STATUS_KEYS = [
  'submitted',
  'verified',
  'payment_pending',
  'under_review',
  'hold_complaint',
  'hold_clearance',
  'correction',
  'sw_review_pending',
  'endorsed',
  'committee_review',
  'approved',
  'rejected',
  'appeal_submitted',
  'permit_approved',
  'permit_collected',
  'coc_pending',
  'coc_issued',
  'closed',
];

export const getStatusToneClass = (status) => STATUS_TONES[toCanonicalStatusKey(status)] || STATUS_TONES.draft;

export const getStatusFilterOptions = () => ([
  { value: '', label: 'All Statuses' },
  ...FILTER_STATUS_KEYS.map((key) => ({ value: key, label: getStatusLabel(key) })),
]);
